export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as Body } from './Body/Body'
export { default as Data } from './Body/Data'
export { default as Numero } from './Numero'